### ISSUE TITLE
getting "-1.0" when trying to retrieve brightness

### ISSUE THREAD

**Issue by nikshulipa** [fiscal-cliff/phonegap-plugin-brightness#11]
my code is exactly the same as in readme. Calling `getBrightness` function give me string '1.0' in callback.
What am I doing wrong?

**Comment by fiscal-cliff** [comment]
Ok, let's check the source
Assuming that you are developing an android application (for instance), we would see `Double brightness = (double) layoutParams.screenBrightness;`, then we open a [developer page](http://developer.android.com/reference/android/view/WindowManager.LayoutParams.html#screenBrightness)
`This can be used to override the user's preferred brightness of the screen. A value of less than 0, the default, means to use the preferred screen brightness. 0 to 1 adjusts the brightness from dark to full bright.`
So it would seem that you have 100% brightness setting on your mobile device. Please note, that hardware features will work correctly only on real device.

**Comment by nikshulipa** [comment]
sorry, didn't mention platform.
Android 5.1.1, Nexus 4
and previous my settings was 'auto'
but now I've noticed that get "-1.0" even if I changed brigtness.
Moreover, trying to set brightness via `setBrigthness` function - got 'OK', but nothing actually change on a screen. BUT! after calling `.setBrigthness(87, /*...*/)` and then `getBrightness` gives me 87.

**Comment by fiscal-cliff** [comment]
Ok, You also should noticed that correct value must be in range from 0 to 1 and also it should be floating point value. Why are you trying to set 87 as a brightness value?

**Comment by nikshulipa** [comment]
thanks, now works fine!
