### ISSUE TITLE
Android Lollipop 5

### ISSUE THREAD

**Issue by evski** [fiscal-cliff/phonegap-plugin-brightness#13]
Plugin has stopped working for me in Lollipop, I believe there's changes in the way brightness works. Has anyone else experienced this?

**Comment by fiscal-cliff** [comment]
Hi, check out the [issue](https://github.com/fiscal-cliff/phonegap-plugin-brightness/issues/12) where we discussed different Android versions running the demos.

**Comment by evski** [comment]
Thanks for response, just tried hello world app in that thread and it doesn’t change the brightness. I’m running android 5.1.1

**Comment by fiscal-cliff** [comment]
So, I've upgraded to mashmallow recently. The os looks pretty similar to 5.1.1. And demo works as expected. Try to do the things bellow:
1. Add logcat output of example program (here)[https://build.phonegap.com/apps/1607546]
2. Ensure that this example doesn't work on other devices, you may test.
3. Describe what you see when the demo starts, and why you decided that it doesn't work.

**Comment by evski** [comment]
1. does the app have a tag set so I can filter it using logcat?
2. I’ve tried on another device running android 4.4.4 and brightness does not change so same behaviour as on 5.1
3. when loading demo app I see loading graphic then x3 buttons, clicking on each I see the alert but no change in brightness

**Comment by fiscal-cliff** [comment]
What's on alert?
Try to dim the screen brightness to the minimum level, using os interface. Then start the application. Turn off the lights in your room. Push a button with set 1. You will see alert OK and brightness will be incresased gradually right after you close the alert. Am I right?

**Comment by evski** [comment]
I just disabled an app called 'GMD immersive' (which allows apps to go full screen) and now it works, somehow that must have been conflicting. Thanks for support.
