### ISSUE TITLE
How to build for build.phonegap.com

### ISSUE THREAD

**Issue by ucci** [fiscal-cliff/phonegap-plugin-brightness#15]
Hello,

Thanks for writing this plugin. Your plugin is so excellent. It works perfect for me.

I'd like to share the tips that how to build this plugin on build.phonegap.com.

just add to config.xml 

`<plugin spec="https://github.com/fiscal-cliff/phonegap-plugin-brightness.git" source="git" />`

Environment: cli-6.5.0 

Thanks.

**Comment by fiscal-cliff** [comment]
could you make a pull request, please?

**Comment by ucci** [comment]
Hi. Thank you for your comment. I've created the pull request.
fiscal-cliff/phonegap-plugin-brightness#16
