### ISSUE TITLE
Unable to return value using getBrightness

### ISSUE THREAD

**Issue by remib** [fiscal-cliff/phonegap-plugin-brightness#5]
How do I get the current brightness? I'm able to use setBrightness and pass it a value but getBrightness doesn't seem to work.

Thanks

**Comment by tmaximini** [comment]
I just get undefined on iOS from getBrightness()

**Comment by fiscal-cliff** [comment]
The getBrightness() MUST return nothing since all the functions requires native calls should return values using callback. The win function has an argument, that returns brightness value.

callbackContext.success(Float.toString(brightness/255)); //returns value 0.0-1.0

**Comment by tmaximini** [comment]
@fiscal-cliff Thanks for clarification! It works now.
